### ISSUE TITLE
Create an autocomplete feature for addresses

### ISSUE THREAD

**Issue by jungshadow** [jungshadow/yfpp#104]
### Expected behavior
As a user starts to type an address into the search box, an autocomplete list appears to help them complete the proper address.

### Actual behavior
No autocomplete appears.

### Steps to reproduce the behavior
Type into the search box.

**Comment by jungshadow** [comment]
Going to use the [Mapbox Geocoding API](https://docs.mapbox.com/api/search/#forward-geocoding) for this.

**Comment by jajohnso** [comment]
Done.
