### ISSUE TITLE
Replace react-addons-css-transition-group package with react-transition-group

### ISSUE THREAD

**Issue by jungshadow** [jungshadow/yfpp#105]
The `react-addons-css-transition-group` package is 3 years out of date and the maintainers [pushed for folks to update to the `react-transition-group` package](https://www.npmjs.com/package/react-addons-css-transition-group). In addition, the `react-transition-group` maintainers [have asked everyone to update to the latest version](https://github.com/reactjs/react-transition-group) as the version that's hot-swappable with our build is no longer maintained. Thankfully, we only have a couple of places to update:

```zsh
% grep -r "react-addons-css-transition-group" src/.
src/./components/Tabs.js:import CSSTransitionGroup from 'react-addons-css-transition-group';
src/./App.js:import CSSTransitionGroup from 'react-addons-css-transition-group';
```

Should be a relatively easy fix.

**Comment by jajohnso** [comment]
I'd like to swap this out for Framer Motion. Also, I don't think it's being used anymore. There's some file cleanup that needs to happen.

**Comment by jajohnso** [comment]
Looks like it's just in the Tabs component, which is cool because we're not using it now that we have the router.
