### ISSUE TITLE
Add electionId to voterInfoQuery based on most relevant current election for a current address

### ISSUE THREAD

**Issue by jungshadow** [jungshadow/yfpp#109]
### Expected behavior
Ability for user to get the most relevant election information and be able to switch to another relevant election.

### Actual behavior
Only the most relevant election to the address is selected. The general election is entirely obscured unless queries explicitly.

### Steps to reproduce the behavior
Query this Atlanta GA address 385 Angier Ct NE Atlanta, GA 30312 before 9/29, the end of the special election.

**Comment by jajohnso** [comment]
Completed.
