### ISSUE TITLE
Add Google type-ahead for address entry

### ISSUE THREAD

**Issue by jungshadow** [jungshadow/yfpp#13]
Right now, the address has to be entered correctly. A Google Maps address type-ahead would make things infinitely easier for users. It would still allow the user to submit whatever they type, but, if the correct address is displayed by the type-ahead, the user could immediately select it instead of continuing to type.

**Comment by nickcatal** [comment]
@jungshadow does the API key included in this have sufficient Places API access? The one we used last time was my separate key.

**Comment by nickcatal** [comment]
@jungshadow you do not have Places API access. Going to use mine for now but we should swap out ASAP.
